version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: vault_db
      MYSQL_USER: vault_user
      MYSQL_PASSWORD: vault_password
    ports:
      - "3306:3306"
    volumes:
      - vault-db-data:/var/lib/mysql

volumes:
  vault-db-data:
